name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /mnt/tredora/tredora-backend
            git fetch --all
            git reset --hard origin/main
            
            docker compose down --volumes --remove-orphans
            docker rmi $(docker images -q tredora-backend-backend) -f || true

            docker compose build --no-cache backend
            docker compose up -d

            docker exec tredora-backend npm run build
            
            docker restart tredora-backend

            docker image prune -f
            docker builder prune -f
